sudo: required
dist: trusty

language: haxe

haxe:
 - "4.0.0-rc.3"

install:
 - haxelib git dox https://github.com/HaxeFoundation/dox.git
 - haxelib git hxmath https://github.com/tbrosman/hxmath.git
 - haxelib install heaps
 - haxelib install ghostlib
 - haxelib dev echo .

script:
 - haxe test.hxml
 - haxe sample.hxml
 - haxe dox.hxml

deploy:
 - provider: pages
   local-dir: bin
   skip-cleanup: true
   github-token: $GITHUB_TOKEN
   on:
    tags: true
 - provider: script
   haxe: "4.0.0-rc.3"
   script: bash ./release_haxelib.sh $HAXELIB_PWD
   on:
    tags: true
    
